
server:
  port: 6060

eureka:
  client:
    #将可用区映射到与eureka服务器通信的完全限定URL列表
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka/



management:
  info:
    git:
      enabled: true



spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          username: 2329073340@qq.com
          password: 2329073340lin
          uri: https://gitee.com/changenen/congfig_server.git
          timeout: 60
          default-label: master
    inetutils:
      timeout-seconds: 60







